# Generated by Django 5.1.6 on 2025-03-18 14:54

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [VectorExtension()]
