# Generated by Django 5.1.6 on 2025-03-18 15:06

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_enable_pgvector'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileattachment',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, editable=False, null=True),
        ),
    ]
