# Generated by Django 5.1.6 on 2025-03-20 10:30

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_fileattachment_content_fileattachment_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileattachment',
            name='content',
        ),
        migrations.RemoveField(
            model_name='fileattachment',
            name='embedding',
        ),
        migrations.CreateModel(
            name='FileEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('metadata', models.JSONField()),
                ('file_attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='app.fileattachment')),
            ],
        ),
    ]
