# Generated by Django 5.1.6 on 2025-03-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_fileattachment_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileembedding',
            name='metadata',
            field=models.TextField(blank=True, null=True),
        ),
    ]
