# Generated by Django 5.1.6 on 2025-03-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_fileembedding_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileembedding',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
