# Generated by Django 5.1.6 on 2025-03-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_fileembedding_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileattachment',
            name='file',
            field=models.FileField(max_length=400, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
